### PR TITLE
fix: Tags, keyboard accesibility [WEB-1852]

### PR DESCRIPTION
**Pull request by johnkim-det**
- Adds `tabIndex` to allow navigation with Tab key
- Adds event handlers to Add and Edit Tags with Enter key and Delete Tags with Backspace
- Also changing Link to always fire click handler on Enter press
- Also adjusting Tag edit to prevent creating duplicates when no exiting without change

### CODE REVIEW

**Review by gt2345 — APPROVED** [review]
Adding/Editing/Deleting tag all work as expected through keyboard, thanks for the improvement

**Comment by julian-determined-ai** [comment]
This tag work looks great! Can we make the tag inputs lose focus with the press of the `escape` key, so that it matches the `escape` functionality with the rest of the inputs in hew.

**Comment by johnkim-det** [comment]
> @johnkim-det
> 
> This tag work looks great! Can we make the tag inputs lose focus with the press of the `escape` key, so that it matches the `escape` functionality with the rest of the inputs in Hew?

Can definitely add that, but just want to confirm that it's an accessibility requirement. I'm actually not seeing that behavior in our other input components (or in antd, MDN examples).

**Comment by julian-determined-ai** [comment]
> > @johnkim-det
> > This tag work looks great! Can we make the tag inputs lose focus with the press of the `escape` key, so that it matches the `escape` functionality with the rest of the inputs in Hew?
> 
> Can definitely add that, but just want to confirm that it's an accessibility requirement. I'm actually not seeing that behavior in our other input components (or in antd, MDN examples).

This is interesting, I did implement this here https://hpe-aiatscale.atlassian.net/browse/WEB-1251 and here https://github.com/determined-ai/determined/pull/7859 but looks like it might not have gotten ported over to Hew, but maybe that can be handled in another ticket which can also mention looking at the tag escape functionality.

**Review by julian-determined-ai — APPROVED** [review]

**Pull request merged**
