### PR TITLE
fix: improve chart grid scrolling behavior [ET-42]

### PR DESCRIPTION
**Pull request by EmilyBonar**
On the [react-virtuoso Troubleshooting page](https://virtuoso.dev/troubleshooting/) it says that margins can cause issues scrolling to the bottom, so I went through and removed them.

Scroll up and down on the new "Inside scrolling container" example in the ChartGrid section.

### CODE REVIEW

**Review by keita-determined — COMMENTED** [review]
i can still reproduce it.

https://github.com/determined-ai/hew/assets/109113616/e8e6e744-78ea-40d9-9b0c-870284914adb

**Comment by keita-determined** [comment]
this is  definitely better than before cuz i can reach the end, but still see it.

https://github.com/determined-ai/hew/assets/109113616/811c08ac-6d38-4173-831a-89736f8a829f

**Comment by keita-determined** [comment]
@EmilyBonar can we close this PR?

**Comment by EmilyBonar** [comment]
No fix found

**Pull request closed without merging**
